# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
    { :hostname => 'vmdebian', :ip => "10.11.12.13", :memory => "1024", :cpu => "1", :boxname => "generic/debian11" },
    { :hostname => 'vmalma', :ip => "10.11.12.14", :memory => "1024", :cpu => "1", :boxname => "almalinux/9" },
]

Vagrant.configure("2") do |config|

    nodes.each do |node|
        config.vm.box_check_update = false
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:boxname]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            nodeconfig.vm.provider "vmware_desktop" do |v|
                v.gui = false
                v.memory = node[:memory]
                v.cpus = node[:cpu]
                v.linked_clone = false
            end
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "setup-playbook.yml"
    end

end
